//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScoreoForERLite.App.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class I18N {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal I18N() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScoreoForERLite.App.Resources.I18N", typeof(I18N).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score-O / Rogaining scores for EResults Lite.
        /// </summary>
        internal static string About_Description {
            get {
                return ResourceManager.GetString("About_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score-O for EResults Lite.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        internal static string Export_Results_Title {
            get {
                return ResourceManager.GetString("Export_Results_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Splits.
        /// </summary>
        internal static string Export_Splits_Title {
            get {
                return ResourceManager.GetString("Export_Splits_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to html files (*.html)|*.html|All files (*.*)|*.*.
        /// </summary>
        internal static string ExportToHtmlDialog_Filter {
            get {
                return ResourceManager.GetString("ExportToHtmlDialog_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results file.
        /// </summary>
        internal static string ExportToHtmlDialog_ResultsFile {
            get {
                return ResourceManager.GetString("ExportToHtmlDialog_ResultsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to results.
        /// </summary>
        internal static string ExportToHtmlDialog_ResultsFileSuffix {
            get {
                return ResourceManager.GetString("ExportToHtmlDialog_ResultsFileSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event title.
        /// </summary>
        internal static string ExportToHtmlDialog_ResultsTitle {
            get {
                return ResourceManager.GetString("ExportToHtmlDialog_ResultsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Splits file.
        /// </summary>
        internal static string ExportToHtmlDialog_SplitsFile {
            get {
                return ResourceManager.GetString("ExportToHtmlDialog_SplitsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to splits.
        /// </summary>
        internal static string ExportToHtmlDialog_SplitsFileSuffix {
            get {
                return ResourceManager.GetString("ExportToHtmlDialog_SplitsFileSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export results to HTML.
        /// </summary>
        internal static string ExportToHtmlDialog_Title {
            get {
                return ResourceManager.GetString("ExportToHtmlDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emit.
        /// </summary>
        internal static string MainGridHeader_EmitCode {
            get {
                return ResourceManager.GetString("MainGridHeader_EmitCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string MainGridHeader_EventTime {
            get {
                return ResourceManager.GetString("MainGridHeader_EventTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string MainGridHeader_FullName {
            get {
                return ResourceManager.GetString("MainGridHeader_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penalty.
        /// </summary>
        internal static string MainGridHeader_PenaltyScore {
            get {
                return ResourceManager.GetString("MainGridHeader_PenaltyScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punches.
        /// </summary>
        internal static string MainGridHeader_Punches {
            get {
                return ResourceManager.GetString("MainGridHeader_Punches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        internal static string MainGridHeader_Rank {
            get {
                return ResourceManager.GetString("MainGridHeader_Rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        internal static string MainGridHeader_Score {
            get {
                return ResourceManager.GetString("MainGridHeader_Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string MainGridHeader_TotalScore {
            get {
                return ResourceManager.GetString("MainGridHeader_TotalScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string MenuItem_About {
            get {
                return ResourceManager.GetString("MenuItem_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always on top.
        /// </summary>
        internal static string MenuItem_AlwaysOnTop {
            get {
                return ResourceManager.GetString("MenuItem_AlwaysOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always on top.
        /// </summary>
        internal static string MenuItem_AlwaysOnTop1 {
            get {
                return ResourceManager.GetString("MenuItem_AlwaysOnTop1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto show latest result.
        /// </summary>
        internal static string MenuItem_AutoShowLatest {
            get {
                return ResourceManager.GetString("MenuItem_AutoShowLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string MenuItem_Exit {
            get {
                return ResourceManager.GetString("MenuItem_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export results.
        /// </summary>
        internal static string MenuItem_Export {
            get {
                return ResourceManager.GetString("MenuItem_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML....
        /// </summary>
        internal static string MenuItem_Export_html {
            get {
                return ResourceManager.GetString("MenuItem_Export_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string MenuItem_File {
            get {
                return ResourceManager.GetString("MenuItem_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string MenuItem_Help {
            get {
                return ResourceManager.GetString("MenuItem_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string MenuItem_Open {
            get {
                return ResourceManager.GetString("MenuItem_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string MenuItem_Settings {
            get {
                return ResourceManager.GetString("MenuItem_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string MenuItem_View {
            get {
                return ResourceManager.GetString("MenuItem_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No competition file.
        /// </summary>
        internal static string NoCompetitionFileName {
            get {
                return ResourceManager.GetString("NoCompetitionFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Name.
        /// </summary>
        internal static string NoNameName {
            get {
                return ResourceManager.GetString("NoNameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  EResultLite file (*.json)|*.json|All files (*.*)|*.*.
        /// </summary>
        internal static string OpenCompetitionFile_Filter {
            get {
                return ResourceManager.GetString("OpenCompetitionFile_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank.
        /// </summary>
        internal static string ResultDetails_Rank {
            get {
                return ResourceManager.GetString("ResultDetails_Rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result: .
        /// </summary>
        internal static string ResultDetails_Title {
            get {
                return ResourceManager.GetString("ResultDetails_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string ResultGridHeader_PunchCode {
            get {
                return ResourceManager.GetString("ResultGridHeader_PunchCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split.
        /// </summary>
        internal static string ResultGridHeader_SplitTime {
            get {
                return ResourceManager.GetString("ResultGridHeader_SplitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total score.
        /// </summary>
        internal static string ResultGridHeader_TotalScore {
            get {
                return ResourceManager.GetString("ResultGridHeader_TotalScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed controls.
        /// </summary>
        internal static string Settings_AllowedControls {
            get {
                return ResourceManager.GetString("Settings_AllowedControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed control codes and points for the codes. If points are missing they are calculated using the scoring function. 
        ///Comman separated list in following format is used: &lt;code1&gt;[:&lt;points1&gt;],&lt;codeN&gt;[:&lt;pointsN&gt;]. 
        ///e.g 31,32:9,33:5,80,100.
        /// </summary>
        internal static string Settings_AllowedControls_Description {
            get {
                return ResourceManager.GetString("Settings_AllowedControls_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish control code.
        /// </summary>
        internal static string Settings_FinishControl {
            get {
                return ResourceManager.GetString("Settings_FinishControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code of the finish control..
        /// </summary>
        internal static string Settings_FinishControl_Description {
            get {
                return ResourceManager.GetString("Settings_FinishControl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string Settings_Group_General {
            get {
                return ResourceManager.GetString("Settings_Group_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scoring.
        /// </summary>
        internal static string Settings_Group_Scoring {
            get {
                return ResourceManager.GetString("Settings_Group_Scoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading settings failed: {0}.
        /// </summary>
        internal static string Settings_LoadFromCompetition_Error {
            get {
                return ResourceManager.GetString("Settings_LoadFromCompetition_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max time (hh:mm:ss).
        /// </summary>
        internal static string Settings_MaxTime {
            get {
                return ResourceManager.GetString("Settings_MaxTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximun time for the performance after which penalty points are calculated..
        /// </summary>
        internal static string Settings_MaxTime_Description {
            get {
                return ResourceManager.GetString("Settings_MaxTime_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximun time for the performance after which penalty points are calculated..
        /// </summary>
        internal static string Settings_MaxTime_Description1 {
            get {
                return ResourceManager.GetString("Settings_MaxTime_Description1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penalty interval in seconds..
        /// </summary>
        internal static string Settings_PenaltyInterval_Description {
            get {
                return ResourceManager.GetString("Settings_PenaltyInterval_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penalty interval (s).
        /// </summary>
        internal static string Settings_PenaltyIntervalSeconds {
            get {
                return ResourceManager.GetString("Settings_PenaltyIntervalSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penalty is calculated for every new interval..
        /// </summary>
        internal static string Settings_PenaltyIntervalSeconds_Description {
            get {
                return ResourceManager.GetString("Settings_PenaltyIntervalSeconds_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penalty per interval.
        /// </summary>
        internal static string Settings_PenaltyPerInterval {
            get {
                return ResourceManager.GetString("Settings_PenaltyPerInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penalty points for every starting penalty interval.
        /// </summary>
        internal static string Settings_PenaltyPerInterval_Description {
            get {
                return ResourceManager.GetString("Settings_PenaltyPerInterval_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reader control code.
        /// </summary>
        internal static string Settings_ReaderControl {
            get {
                return ResourceManager.GetString("Settings_ReaderControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code of the reader control code.
        /// </summary>
        internal static string Settings_ReaderControl_Description {
            get {
                return ResourceManager.GetString("Settings_ReaderControl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scoring function name.
        /// </summary>
        internal static string Settings_ScoringFunctionName {
            get {
                return ResourceManager.GetString("Settings_ScoringFunctionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formula for converting control codes to points.
        ///Code = points: e.g. 32 =&gt; 32
        ///1st number = points: e.g. 32 =&gt; 3, 131 =&gt; 13
        ///1st number = points (max 10): e.g. 32 =&gt; 3, 131 =&gt; 10.
        /// </summary>
        internal static string Settings_ScoringFunctionName_Description {
            get {
                return ResourceManager.GetString("Settings_ScoringFunctionName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start control code.
        /// </summary>
        internal static string Settings_StartControl {
            get {
                return ResourceManager.GetString("Settings_StartControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control code that starts the timing.
        /// </summary>
        internal static string Settings_StartControl_Description {
            get {
                return ResourceManager.GetString("Settings_StartControl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied to clipboard. Paste it to EResults Course controls.
        /// </summary>
        internal static string SettingsCopiedClipboard {
            get {
                return ResourceManager.GetString("SettingsCopiedClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsDialog_Title {
            get {
                return ResourceManager.GetString("SettingsDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event:.
        /// </summary>
        internal static string StatusLabel_EventDetails {
            get {
                return ResourceManager.GetString("StatusLabel_EventDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last updated:.
        /// </summary>
        internal static string StatusLabel_LastUpdated {
            get {
                return ResourceManager.GetString("StatusLabel_LastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results:.
        /// </summary>
        internal static string StatusLabel_Results {
            get {
                return ResourceManager.GetString("StatusLabel_Results", resourceCulture);
            }
        }
    }
}
